
"use strict";

const WM = "-- this file was generated by oxygen Deobf | https://discord.gg/Cd4uvQBGq";

function withWatermark(code) {
    if (code.indexOf(WM) === 0) return code;
    return WM + "\n\n" + code;
}

function ensureSource(src, maxMB) {
    if (typeof src !== "string") throw new Error("source must be a string");
    if (src.length === 0) throw new Error("empty source");
    const max = (maxMB || 32) * 1024 * 1024;
    if (src.length > max) throw new Error("file too large (max " + (maxMB || 32) + " MB)");
}

function guardRun(fn) {
    try {
        return { ok: true, result: fn() };
    } catch (err) {
        return { ok: false, error: err && err.message ? err.message : String(err) };
    }
}

module.exports = { WM, withWatermark, ensureSource, guardRun };
